Tiago-O/go-goats

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20210508150213_devise_create_users.rb
db/migrate/20210508151342_add_name_to_users.rb
db/migrate/20210508151513_add_address_to_users.rb
db/schema.rb
test/models/user_test.rb

Please the code for the sign up and login pages

Inserted sign up and login pages

---

config/routes.rb

create routes users, goats, reserves and reviews

---

app/models/review.rb
db/migrate/20210511182250_create_reviews.rb
test/models/review_test.rb

Added Review model

---

app/models/goat.rb
app/models/reservation.rb
app/models/review.rb
app/models/user.rb

Check the associations and validations

added associations and validations

---

config/routes.rb

changer routes reserves for reservations

---

app/views/goats/show.html.erb

view goats show created

---

app/views/goats/edit.html.erb
app/views/goats/index.html.erb

Check the view for goat index and edit

created view for goat index and edit

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/views/goats/new.html.erb

Added new and create view for goats

---

app/controllers/goats_controller.rb

Changed create goats controller

---

app/models/reservation.rb

deleted validation availability date

---

app/assets/stylesheets/components/_cards.scss

Fixed the create form, removed height

---

app/controllers/goats_controller.rb
app/controllers/reviews_controller.rb
app/views/goats/show.html.erb

Check the review form in the goats show view

inserted reviews and reviews form in goats show view

---

app/controllers/users_controller.rb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb

Added view for users and the link to from profile bootstap button

Added the linkto profile and show view

---

app/controllers/goats_controller.rb
app/controllers/reservations_controller.rb
app/views/goats/show.html.erb

modal reservation in the goats show created

---

db/seeds.rb

Seeds file

---

app/views/goats/components/_card.html.erb
app/views/goats/index.html.erb

started to create card index goats

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/components/_banner.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

Check the front end of the home page

Adapted the home page front end

---

app/controllers/reservations_controller.rb
app/views/goats/components/_modal.html.erb
app/views/pages/home.html.erb
app/views/reservations/create.html.erb
app/views/reservations/edit.html.erb
app/views/reservations/new.html.erb
config/routes.rb

Check the confirmation page, after you have reserved a herd

Corrected photos home page and confirmation page

---

app/models/goat.rb
app/views/users/show.html.erb

Need to check the users profile

Added Herds and Reservations to users profile and link to

---

app/assets/stylesheets/components/_cards.scss
app/controllers/goats_controller.rb
app/controllers/pages_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/goats/components/_card-goat.html.erb
app/views/goats/index.html.erb
app/views/pages/home.html.erb

goats index with map

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/application_controller.rb
app/controllers/goats_controller.rb
app/controllers/pages_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/goats/components/_card-goat.html.erb
app/views/goats/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Navbar change

---

app/models/reservation.rb
app/views/goats/index.html.erb

date validations inserted

---

Gemfile
Gemfile.lock
db/seeds.rb

please review
run rails db:seed after

now we have longer comments and descriptions

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show_goats.scss
app/controllers/goats_controller.rb
app/models/review.rb
app/views/goats/show.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/layouts/application.html.erb
config/initializers/kaminari_config.rb
package.json
yarn.lock

goats show front end
